import './globals.css'
import type { Metadata } from 'next'
import { Sen } from 'next/font/google'
import WagmiProvider from './WagmiProvider'

const sen = Sen({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'FetaERC1155',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" data-theme="light">
      <WagmiProvider>
          <body className={sen.className}>{children}</body>
      </WagmiProvider>
    </html>
  )
}
